catalogo/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'catalogo'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^observ$', login_required(views.ObservView), name='observ'),
    url(r'^imageViewer/(?P<id>[0-9]+)/(?P<idcomment>[0-9]+)/$', login_required(views.ImageViewer), name='imageViewer'),
    url(r'^imageViewer/(?P<id>[0-9]+)/$', login_required(views.ImageViewer2), name='imageViewer2'),

    url(r'^(?P<pk>[0-9]+)/$',views.DiseasesView.as_view(), name='diseases'),
    # url(r'^(?P<pk>[0-9]+)/$',views.ImageskinView.as_view(), name='imageskin'),
    # url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # url(r'^(?P<category_id>[0-9]+)/state/$', views.state, name='state'),
    url(r'^changeState$', views.changeState, name='changeState'),
    url(r'^commentPush$', views.commentPush, name='commentPush'),
    url(r'^commentsLoad$', views.listComments, name='commentsLoad'),
    url(r'^getStatusCategory$', views.getStatusCategory, name='getStatusCategory'),
    url(r'^getStatusDisease_by_Category/(?P<id>[0-9]+)/$', views.getStatusDisease_by_Category, name='getStatusDisease_by_Category'),
    url(r'^getStatusSource_by_Category/(?P<id>[0-9]+)/$', views.getStatusSource_by_Category,
        name='getStatusSource_by_Category'),

    # url(r'^upload_image$', views.upload_image, name='uploadImage'),
    url(r'^disease/(?P<pk>[0-9]+)/$', views.ImageskinView.as_view(), name='imageskin'),
    url(r'^imageskin/(?P<id>[0-9]+)/(?P<page>[0-9]+)/$', views.loadImageskin, name='loadImageskin'),
    url(r'^viewImageskin/(?P<id>[0-9]+)/$', login_required(views.viewImageskin), name='viewImageskin'),
    url(r'^upload/$', login_required(views.DragAndDropUploadView.as_view()), name='drag_and_drop_upload'),
]

editor/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'editor'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^crop$', views.EditorView.as_view(), name='editorView'),
    url(r'^imageskin/(?P<id>[0-9]+)/(?P<page>[0-9]+)/$', views.loadImageskin, name='loadImageskin'),
    url(r'^viewImageskin/(?P<id>[0-9]+)/$', login_required(views.viewImageskin), name='viewImageskin'),
    url(r'^saveCoord$', views.saveCoord, name='saveCoord'),
    url(r'^createCropImage/(?P<idx>[0-9]+)/$', views.createCropImage, name='createCropImage'),
    url(r'^transform_coord/(?P<idx>[0-9]+)/(?P<scale>[0-9]+)/$', views.transformCoord, name='transformCoord'),
    url(r'^generateCropAll/(?P<scale>[0-9]+)/(?P<directory>[\w\-]+)/(?P<resize>[0-9]+)/(?P<type>[\w\-]+)/(?P<select>[\w\-]+)/$', views.generateCropAll, name='generateCropAll'),
    url(r'^changeSelect$', views.changeSelect, name='changeSelect'),
    url(r'^count_crop_image$', views.count_crop_image_by_disease, name='count_crop_image_by_disease'),
]

skinWeb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/catalogo')),
    url(r'^catalogo/', include('catalogo.urls')),
    url(r'^editor/', include('editor.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/', auth_views.login, {'template_name': 'catalogo/login.html'},name='login'),
    url(r'^logout/', auth_views.logout_then_login, name='logout'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogo/models.py
import datetime
from django.db import models
from django.utils import timezone
# from slugify import slugify
from django.contrib.auth.models import User
# Create your models here.


class Sourcedata(models.Model):
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=500, default='')
    pub_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=100)
    state = models.BooleanField(default=True)
    pub_date = models.DateTimeField(default=timezone.now())
    detail = models.CharField(max_length=500, default='')
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return self.name

    def countImage(self):
        idx = self.id
        return Imageskin.objects.all().filter(disease__category=idx).count()


class Disease(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    detail = models.CharField(max_length=1000,blank=True)
    state = models.BooleanField(default=True)
    pub_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.name

    def directory(self):
        return self.name

    def cover(self):
        aux = self.imageskin_set.last()
        if aux:
            return aux.docfile.url
        else:
            return ""

    def count_images(self):
        return self.imageskin_set.all().count()


class Imageskin(models.Model):
    disease = models.ForeignKey(Disease, on_delete=models.CASCADE)
    sourcedata = models.ForeignKey(Sourcedata, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=100)
    docfile = models.FileField(upload_to='dataset', null=True, blank=True)
    description = models.CharField(max_length=1000, default='')
    state = models.BooleanField(default=True)
    select = models.BooleanField(default=False)
    pub_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return str(self.id)+"_"+self.name


class Commentimage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imageskin = models.ForeignKey(Imageskin, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)
    state = models.IntegerField(default=0)
    pub_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return str(self.id)+'_'+self.text+'_'+str(self.user.username)


class Commentuser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    commentimage = models.ForeignKey(Commentimage, on_delete=models.CASCADE)
    state = models.BooleanField(default=True)
    pub_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return str(self.id)+'_C:'+str(self.commentimage.id)+'_U:' + str(self.user.username)


# a = Imageskin.objects.values('disease__category').annotate(Count('disease__category'))
# a = Imageskin.objects.values('disease','disease__category').annotate(Count('disease'))#

# OBTENER TODAS LAS IMAGENES DE UNA CATEGORIA
# i = Imageskin.objects.all().filter(disease__category=5)

catalogo/forms.py
from django import forms

from .models import Imageskin


class ImageskinForm(forms.ModelForm):
    class Meta:
        model = Imageskin
        fields = ('docfile', 'name', 'disease', 'sourcedata',)

catalogo/views.py
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.http import HttpResponse, Http404, HttpResponseRedirect, JsonResponse
from django.template.loader import render_to_string
from django.urls import reverse
from django.views import generic, View
from .models import Category, Disease, Imageskin, Sourcedata, Commentimage, Commentuser
from .forms import ImageskinForm
from django.db.models import Count
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
import time
from django.utils import timezone

# Create your views here.


class IndexView (generic.ListView):
    template_name = 'catalogo/category.html'
    context_object_name = 'list'

    def get_queryset(self):
        return Category.objects.all()


def ObservView(request):
    imageskin = Imageskin.objects.all().filter(state=0)
    total = imageskin.count()
    template_name = 'catalogo/observ.html'
    images = render_to_string('catalogo/ajax/grid-image.html', {'imageskin': imageskin, 'userLog': True})
    return render(request, template_name, {'images': images, 'total': total})


def ImageViewer(request, id, idcomment):
    template_name = 'catalogo/image_viewer.html'
    userLogId = request.user.id
    image = Imageskin.objects.get(id=id)
    message = Commentimage.objects.all().filter(imageskin=id).order_by('-pub_date')

    # Para registrar la vista del usuario
    _user = User.objects.get(id=userLogId)

    try:
        _commentimage = Commentimage.objects.get(id=idcomment)

        try:
            Commentuser.objects.get(user=userLogId, commentimage=idcomment)
        except:
            new = Commentuser(user=_user, commentimage=_commentimage)
            new.save()
    except:
        template_name = 'catalogo/404.html'
        return render(request, template_name)


    # imageDetail = render_to_string('catalogo/ajax/view-image.html', {'image': image, 'message': message, 'userLogId': userLogId})
    return render(request, template_name, {'image': image, 'message': message, 'userLogId': userLogId, 'idcomment':idcomment})


def ImageViewer2(request, id):
    template_name = 'catalogo/image_viewer.html'
    userLogId = request.user.id
    image = Imageskin.objects.get(id=id)
    message = Commentimage.objects.all().filter(imageskin=id).order_by('-pub_date')

    # imageDetail = render_to_string('catalogo/ajax/view-image.html', {'image': image, 'message': message, 'userLogId': userLogId})
    return render(request, template_name, {'image': image, 'message': message, 'userLogId': userLogId})


def listComments(request):
    data = {}
    if request.user.is_authenticated:
        userLogId = request.user.id
        commentuser = Commentuser.objects.all().filter(user=userLogId).values('commentimage')
        comments = Commentimage.objects.all().exclude(id__in=commentuser).exclude(user=userLogId).order_by('-pub_date')
        comments2 = Commentimage.objects.all().filter(id__in=commentuser).exclude(user=userLogId).order_by('-pub_date')[:15]
        # comments = Commentimage.objects.all().exclude(id__in=commentuser).order_by('-pub_date')
        totalNewCom = comments.count()

        total = comments.count()
        data['status'] = True
        data['comments'] = render_to_string('catalogo/ajax/list-comments.html', {'comments': comments, 'comments2': comments2, 'userLog': True})
        data['total'] = totalNewCom
    else:
        data['status'] = False
        data['comments'] = False

    # time.sleep(1)
    return JsonResponse(data)


class DiseasesView(generic.DetailView):
    model = Category
    template_name = 'catalogo/diseases.html'


class ImageskinView(generic.DetailView):
    model = Disease
    template_name = 'catalogo/imageskin.html'


def loadImageskin(request, id, page):

    if request.user.is_authenticated:
        userLog = True
    else:
        userLog = False

    image_list = Imageskin.objects.all().filter(disease=id)
    paginator = Paginator(image_list, 15)
    data = {}
    if int(page) <= paginator.num_pages:
        try:
            imageskin = paginator.page(page)
        except PageNotAnInteger:
            imageskin = paginator.page(1)
        except EmptyPage:
            imageskin = paginator.page(paginator.num_pages)

        # usuario = User.is_authenticated
        data['data'] = render_to_string('catalogo/ajax/grid-image.html', {'imageskin': imageskin, 'userLog': userLog})
    else:
        data['data'] = False

    # time.sleep(1)
    return JsonResponse(data)


def viewImageskin(request, id):
    userLogId = request.user.id
    image = Imageskin.objects.get(id=id)
    message = Commentimage.objects.all().filter(imageskin=id).order_by('-pub_date')
    return render(request,'catalogo/ajax/view-image.html', {'image': image, 'message': message, 'userLogId': userLogId})


class ResultsView(generic.DetailView):
    model = Category
    template_name = 'catalogo/results.html'


class DragAndDropUploadView(View):

    def get(self, request):
        if request.user.is_superuser:
            disease_list = Disease.objects.all()
            source_list = Sourcedata.objects.all()
            image_list = Imageskin.objects.all()
            template_name = 'catalogo/drag_and_drop_upload.html'
            return render(self.request, template_name,
                          {'images': image_list, 'diseases': disease_list, 'sources': source_list})
        else:
            template_name = 'catalogo/404.html'
            return render(self.request, template_name)

    def post(self, request):
        form = ImageskinForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            photo = form.save()

            data = {'is_valid': True, 'name': photo.docfile.name, 'url': photo.docfile.url}
        else:
            data = {'is_valid': False, 'msg': "Formulario incompleto."}
        return JsonResponse(data)

# def index(request):
#     _list = Category.objects.all()
#     context = {'list': _list}
#     return render(request, 'catalogo/index2.html',context)
#
#
# def detail(request, category_id):
#     category = get_object_or_404(Category,pk=category_id)
#     return render(request, 'catalogo/detail.html',{'category':category})

# def results(request, category_id):
#     category = get_object_or_404(Category, pk=category_id)
#     return render(request, 'catalogo/results.html', {'category': category})


def getStatusCategory(request):

    a = Imageskin.objects.values('disease__category').annotate(Count('disease__category'))

    idc = list(a.values_list('disease__category__id'))
    name = list(a.values_list('disease__category__name'))
    count = list(a.values_list('disease__category__count'))

    # return render(request, 'catalogo/results.html', {'data': JsonResponse(data)})

    data = {}
    data['datasets'] = {}
    # data['datasets']['data'] = [(200,),(50,),(600,),(150,),(410,)]
    data['datasets']['data'] = count
    # data['datasets']['backgroundColor'] = ['#ff6384','#ff9f40','#ffcd56','#4bc0c0','#36a2eb']
    data['datasets']['backgroundColor'] = ['#ff6384','#ff9f40','#ffcd56','#4bc0c0','#36a2eb']
    data['datasets']['label'] = 'Categoria'
    # data['labels'] = ["Red","Orange","Yellow","Green", "Blue"]
    data['labels'] = name
    data['idc'] = idc
    return JsonResponse(data)


def getStatusDisease_by_Category(request,id):

    a = Imageskin.objects.values('disease', 'disease__category').annotate(Count('disease')).filter(disease__category=id)

    # idc = list(a.values_list('disease__category__id'))
    name = list(a.values_list('disease__name'))
    count = list(a.values_list('disease__count'))

    data = {}
    data['datasets'] = {}
    data['datasets']['data'] = count
    data['datasets']['backgroundColor'] = ['#ff6384','#ff9f40','#ffcd56','#4bc0c0','#36a2eb']
    data['datasets']['label'] = 'Por tipo'
    data['labels'] = name
    return JsonResponse(data)


def getStatusSource_by_Category(request,id):

    a = Imageskin.objects.values('sourcedata', 'disease__category').annotate(Count('sourcedata')).filter(
        disease__category=id)

    # idc = list(a.values_list('disease__category__id'))
    name = list(a.values_list('sourcedata__name'))
    count = list(a.values_list('sourcedata__count'))

    data = {}
    data['datasets'] = {}
    data['datasets']['data'] = count
    data['datasets']['backgroundColor'] = ['#ff6384','#ff9f40','#ffcd56','#4bc0c0','#36a2eb']
    data['datasets']['label'] = 'Por fuente'
    data['labels'] = name
    return JsonResponse(data)


def changeState(request):

    model_opc = request.POST['model']
    idc = request.POST['id']
    data_state = request.POST['state']

    if model_opc == 'category':
        model_aux = get_object_or_404(Category, pk=idc)
    elif model_opc == 'disease':
        model_aux = get_object_or_404(Disease, pk=idc)
    elif model_opc == 'imageskin':
        model_aux = get_object_or_404(Imageskin, pk=idc)

    if data_state == "true":
        data_state = True
    else:
        data_state = False

    model_aux.state = data_state
    model_aux.save()

    data = {}
    data['status'] = True
    data['state'] = data_state
    data['msg'] = 'Cambio realizado.'
    return JsonResponse(data)


def state(request, category_id):
    category = get_object_or_404(Category,pk=category_id)

    if 'state' in request.POST:
        value = True
    else:
        value = False

    category.state = value
    category.save()

    return HttpResponseRedirect(reverse('catalogo:results', args=(category_id,)))


def commentPush(request):

    data = {}
    if request.user.is_authenticated:
        userLog = request.user.id
    else:
        userLog = False

    idU = User.objects.get(pk=request.user.id)
    idI = Imageskin.objects.get(pk=request.POST['idx'])
    text = request.POST['text']
    textCount = len(text)

    if textCount == 0:
        data['status'] = False

catalogo/templates/catalogo/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %} Rikardocorp {% endblock title %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'catalogo/plugins/bootstrap3/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'catalogo/plugins/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">


    <!-- Custom CSS -->
    <link href="{% static 'catalogo/plugins/startbootstrap/css/2-col-portfolio.css' %}" rel="stylesheet">
    <link href="{% static 'catalogo/plugins/startbootstrap/css/round-about.css' %}" rel="stylesheet">

    {% block stylesheet %}{% endblock stylesheet %}

    <link href="{% static 'catalogo/css/style.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body class="skinWeb">

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        {% include 'catalogo/main/header.html' %}
    </nav>

    <div id="conte-message" style="display: none">
        <div id="skin-message" class="alert alert-warning" role="alert">
            Skin Images
        </div>
    </div>

    <!-- Page Content -->
    <div class="container">

        {% block contenido %}

        {% endblock contenido %}


        <!-- Footer -->
        {% include 'catalogo/main/footer.html' %}

    </div>
    <!-- /.container -->





    <!-- jQuery -->
    <script src="{% static 'catalogo/plugins/jquery/jquery-1.12.4.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'catalogo/plugins/bootstrap3/js/bootstrap.min.js' %}"></script>

    <script>
        $('#skin-message').click(function (){
            $('#conte-message').fadeToggle();
        });

        {# Cargar los comentarios #}
        $.ajax({
            type: 'POST',
            url: '/catalogo/commentsLoad',
            dataType: 'json',
            data: {
                csrfmiddlewaretoken: "{{ csrf_token }}",
            },
            success: function (data, textStatus) {
                if (data.status){
                    $('#dropdown_comments ul.dropdown-menu').html(data.comments);
                    $('#dropdown_comments > a span.badge').html(
                        (data.total==0 ? '' : data.total)
                    );
                }
            },
            error: function(xhr, status, e) {
                alert(status, e);
            }
        });


        {# Para interactuar con los commentarios en el area de notificacion #}
        $('#dropdown_comments').on('click','.dropdown-menu > li', function () {

        });



    </script>
    {% block javascript %}

    {% endblock javascript %}


</body>

</html>

catalogo/templates/catalogo/main/footer.html
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p>Copyright &copy; rikardocorp 2017</p>
        </div>
    </div>
    <!-- /.row -->
</footer>

catalogo/templates/catalogo/main/header.html
<div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'catalogo:index' %}">Skin Diseases</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
{#            <li>#}
{#                <a href="{% url 'catalogo:index' %}">Categorias</a>#}
{#            </li>#}
            <li>
                <a href="{% url 'catalogo:drag_and_drop_upload' %}">Upload</a>
            </li>
            {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'catalogo:observ' %}">Observaciones</a>
                </li>
                <li>
                    <a href="#">{{ user.username }}</a>
                </li>
                <li id="dropdown_comments" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Comentarios <span class="badge"></span><span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'logout' %}">Salir <i class="fa fa-sign-out" aria-hidden="true"></i></a></li>
            {% else %}
                <li>
                    <a href="{% url 'login' %}">Login <i class="fa fa-sign-in" aria-hidden="true"></i></a>
                </li>
            {% endif %}


        </ul>
    </div>
    <!-- /.navbar-collapse -->
</div>
<!-- /.container -->