catalogo/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'catalogo'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^observ$', login_required(views.ObservView), name='observ'),
    url(r'^imageViewer/(?P<id>[0-9]+)/(?P<idcomment>[0-9]+)/$', login_required(views.ImageViewer), name='imageViewer'),
    url(r'^imageViewer/(?P<id>[0-9]+)/$', login_required(views.ImageViewer2), name='imageViewer2'),

    url(r'^(?P<pk>[0-9]+)/$',views.DiseasesView.as_view(), name='diseases'),
    # url(r'^(?P<pk>[0-9]+)/$',views.ImageskinView.as_view(), name='imageskin'),
    # url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # url(r'^(?P<category_id>[0-9]+)/state/$', views.state, name='state'),
    url(r'^changeState$', views.changeState, name='changeState'),
    url(r'^commentPush$', views.commentPush, name='commentPush'),
    url(r'^commentsLoad$', views.listComments, name='commentsLoad'),
    url(r'^getStatusCategory$', views.getStatusCategory, name='getStatusCategory'),
    url(r'^getStatusDisease_by_Category/(?P<id>[0-9]+)/$', views.getStatusDisease_by_Category, name='getStatusDisease_by_Category'),
    url(r'^getStatusSource_by_Category/(?P<id>[0-9]+)/$', views.getStatusSource_by_Category,
        name='getStatusSource_by_Category'),

    # url(r'^upload_image$', views.upload_image, name='uploadImage'),
    url(r'^disease/(?P<pk>[0-9]+)/$', views.ImageskinView.as_view(), name='imageskin'),
    url(r'^imageskin/(?P<id>[0-9]+)/(?P<page>[0-9]+)/$', views.loadImageskin, name='loadImageskin'),
    url(r'^viewImageskin/(?P<id>[0-9]+)/$', login_required(views.viewImageskin), name='viewImageskin'),
    url(r'^upload/$', login_required(views.DragAndDropUploadView.as_view()), name='drag_and_drop_upload'),
]

editor/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'editor'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^crop$', views.EditorView.as_view(), name='editorView'),
    url(r'^imageskin/(?P<id>[0-9]+)/(?P<page>[0-9]+)/$', views.loadImageskin, name='loadImageskin'),
    url(r'^viewImageskin/(?P<id>[0-9]+)/$', login_required(views.viewImageskin), name='viewImageskin'),
    url(r'^saveCoord$', views.saveCoord, name='saveCoord'),
    url(r'^createCropImage/(?P<idx>[0-9]+)/$', views.createCropImage, name='createCropImage'),
    url(r'^transform_coord/(?P<idx>[0-9]+)/(?P<scale>[0-9]+)/$', views.transformCoord, name='transformCoord'),
    url(r'^generateCropAll/(?P<scale>[0-9]+)/(?P<directory>[\w\-]+)/(?P<resize>[0-9]+)/(?P<type>[\w\-]+)/(?P<select>[\w\-]+)/$', views.generateCropAll, name='generateCropAll'),
    url(r'^changeSelect$', views.changeSelect, name='changeSelect'),
    url(r'^count_crop_image$', views.count_crop_image_by_disease, name='count_crop_image_by_disease'),
]

skinWeb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/catalogo')),
    url(r'^catalogo/', include('catalogo.urls')),
    url(r'^editor/', include('editor.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/', auth_views.login, {'template_name': 'catalogo/login.html'},name='login'),
    url(r'^logout/', auth_views.logout_then_login, name='logout'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogo/models.py
import datetime
from django.db import models
from django.utils import timezone
# from slugify import slugify
from django.contrib.auth.models import User
# Create your models here.


class Sourcedata(models.Model):
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=500, default='')
    pub_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=100)
    state = models.BooleanField(default=True)
    pub_date = models.DateTimeField(default=timezone.now())
    detail = models.CharField(max_length=500, default='')
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return self.name

    def countImage(self):
        idx = self.id
        return Imageskin.objects.all().filter(disease__category=idx).count()


class Disease(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    detail = models.CharField(max_length=1000,blank=True)
    state = models.BooleanField(default=True)
    pub_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.name

    def directory(self):
        return self.name

    def cover(self):
        aux = self.imageskin_set.last()
        if aux:
            return aux.docfile.url
        else:
            return ""

    def count_images(self):
        return self.imageskin_set.all().count()


class Imageskin(models.Model):
    disease = models.ForeignKey(Disease, on_delete=models.CASCADE)
    sourcedata = models.ForeignKey(Sourcedata, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=100)
    docfile = models.FileField(upload_to='dataset', null=True, blank=True)
    description = models.CharField(max_length=1000, default='')
    state = models.BooleanField(default=True)
    select = models.BooleanField(default=False)
    pub_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return str(self.id)+"_"+self.name


class Commentimage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imageskin = models.ForeignKey(Imageskin, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)
    state = models.IntegerField(default=0)
    pub_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return str(self.id)+'_'+self.text+'_'+str(self.user.username)


class Commentuser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    commentimage = models.ForeignKey(Commentimage, on_delete=models.CASCADE)
    state = models.BooleanField(default=True)
    pub_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return str(self.id)+'_C:'+str(self.commentimage.id)+'_U:' + str(self.user.username)


# a = Imageskin.objects.values('disease__category').annotate(Count('disease__category'))
# a = Imageskin.objects.values('disease','disease__category').annotate(Count('disease'))#

# OBTENER TODAS LAS IMAGENES DE UNA CATEGORIA
# i = Imageskin.objects.all().filter(disease__category=5)

catalogo/forms.py
from django import forms

from .models import Imageskin


class ImageskinForm(forms.ModelForm):
    class Meta:
        model = Imageskin
        fields = ('docfile', 'name', 'disease', 'sourcedata',)

catalogo/views.py
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.http import HttpResponse, Http404, HttpResponseRedirect, JsonResponse
from django.template.loader import render_to_string
from django.urls import reverse
from django.views import generic, View
from .models import Category, Disease, Imageskin, Sourcedata, Commentimage, Commentuser
from .forms import ImageskinForm
from django.db.models import Count
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
import time
from django.utils import timezone

# Create your views here.


class IndexView (generic.ListView):
    template_name = 'catalogo/category.html'
    context_object_name = 'list'

    def get_queryset(self):
        return Category.objects.all()


def ObservView(request):
    imageskin = Imageskin.objects.all().filter(state=0)
    total = imageskin.count()
    template_name = 'catalogo/observ.html'
    images = render_to_string('catalogo/ajax/grid-image.html', {'imageskin': imageskin, 'userLog': True})
    return render(request, template_name, {'images': images, 'total': total})


def ImageViewer(request, id, idcomment):
    template_name = 'catalogo/image_viewer.html'
    userLogId = request.user.id
    image = Imageskin.objects.get(id=id)
    message = Commentimage.objects.all().filter(imageskin=id).order_by('-pub_date')

    # Para registrar la vista del usuario
    _user = User.objects.get(id=userLogId)

    try:
        _commentimage = Commentimage.objects.get(id=idcomment)

        try:
            Commentuser.objects.get(user=userLogId, commentimage=idcomment)
        except:
            new = Commentuser(user=_user, commentimage=_commentimage)
            new.save()
    except:
        template_name = 'catalogo/404.html'
        return render(request, template_name)


    # imageDetail = render_to_string('catalogo/ajax/view-image.html', {'image': image, 'message': message, 'userLogId': userLogId})
    return render(request, template_name, {'image': image, 'message': message, 'userLogId': userLogId, 'idcomment':idcomment})


def ImageViewer2(request, id):
    template_name = 'catalogo/image_viewer.html'
    userLogId = request.user.id
    image = Imageskin.objects.get(id=id)
    message = Commentimage.objects.all().filter(imageskin=id).order_by('-pub_date')

    # imageDetail = render_to_string('catalogo/ajax/view-image.html', {'image': image, 'message': message, 'userLogId': userLogId})
    return render(request, template_name, {'image': image, 'message': message, 'userLogId': userLogId})


def listComments(request):
    data = {}
    if request.user.is_authenticated:
        userLogId = request.user.id
        commentuser = Commentuser.objects.all().filter(user=userLogId).values('commentimage')
        comments = Commentimage.objects.all().exclude(id__in=commentuser).exclude(user=userLogId).order_by('-pub_date')
        comments2 = Commentimage.objects.all().filter(id__in=commentuser).exclude(user=userLogId).order_by('-pub_date')[:15]
        # comments = Commentimage.objects.all().exclude(id__in=commentuser).order_by('-pub_date')
        totalNewCom = comments.count()

        total = comments.count()
        data['status'] = True
        data['comments'] = render_to_string('catalogo/ajax/list-comments.html', {'comments': comments, 'comments2': comments2, 'userLog': True})
        data['total'] = totalNewCom
    else:
        data['status'] = False
        data['comments'] = False

    # time.sleep(1)
    return JsonResponse(data)


class DiseasesView(generic.DetailView):
    model = Category
    template_name = 'catalogo/diseases.html'


class ImageskinView(generic.DetailView):
    model = Disease
    template_name = 'catalogo/imageskin.html'


def loadImageskin(request, id, page):

    if request.user.is_authenticated:
        userLog = True
    else:
        userLog = False

    image_list = Imageskin.objects.all().filter(disease=id)
    paginator = Paginator(image_list, 15)
    data = {}
    if int(page) <= paginator.num_pages:
        try:
            imageskin = paginator.page(page)
        except PageNotAnInteger:
            imageskin = paginator.page(1)
        except EmptyPage:
            imageskin = paginator.page(paginator.num_pages)

        # usuario = User.is_authenticated
        data['data'] = render_to_string('catalogo/ajax/grid-image.html', {'imageskin': imageskin, 'userLog': userLog})
    else:
        data['data'] = False

    # time.sleep(1)
    return JsonResponse(data)


def viewImageskin(request, id):
    userLogId = request.user.id
    image = Imageskin.objects.get(id=id)
    message = Commentimage.objects.all().filter(imageskin=id).order_by('-pub_date')
    return render(request,'catalogo/ajax/view-image.html', {'image': image, 'message': message, 'userLogId': userLogId})


class ResultsView(generic.DetailView):
    model = Category
    template_name = 'catalogo/results.html'


class DragAndDropUploadView(View):

    def get(self, request):
        if request.user.is_superuser:
            disease_list = Disease.objects.all()
            source_list = Sourcedata.objects.all()
            image_list = Imageskin.objects.all()
            template_name = 'catalogo/drag_and_drop_upload.html'
            return render(self.request, template_name,
                          {'images': image_list, 'diseases': disease_list, 'sources': source_list})
        else:
            template_name = 'catalogo/404.html'
            return render(self.request, template_name)

    def post(self, request):
        form = ImageskinForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            photo = form.save()

            data = {'is_valid': True, 'name': photo.docfile.name, 'url': photo.docfile.url}
        else:
            data = {'is_valid': False, 'msg': "Formulario incompleto."}
        return JsonResponse(data)

# def index(request):
#     _list = Category.objects.all()
#     context = {'list': _list}
#     return render(request, 'catalogo/index2.html',context)
#
#
# def detail(request, category_id):
#     category = get_object_or_404(Category,pk=category_id)
#     return render(request, 'catalogo/detail.html',{'category':category})

# def results(request, category_id):
#     category = get_object_or_404(Category, pk=category_id)
#     return render(request, 'catalogo/results.html', {'category': category})


def getStatusCategory(request):

    a = Imageskin.objects.values('disease__category').annotate(Count('disease__category'))

    idc = list(a.values_list('disease__category__id'))
    name = list(a.values_list('disease__category__name'))
    count = list(a.values_list('disease__category__count'))

    # return render(request, 'catalogo/results.html', {'data': JsonResponse(data)})

    data = {}
    data['datasets'] = {}
    # data['datasets']['data'] = [(200,),(50,),(600,),(150,),(410,)]
    data['datasets']['data'] = count
    # data['datasets']['backgroundColor'] = ['#ff6384','#ff9f40','#ffcd56','#4bc0c0','#36a2eb']
    data['datasets']['backgroundColor'] = ['#ff6384','#ff9f40','#ffcd56','#4bc0c0','#36a2eb']
    data['datasets']['label'] = 'Categoria'
    # data['labels'] = ["Red","Orange","Yellow","Green", "Blue"]
    data['labels'] = name
    data['idc'] = idc
    return JsonResponse(data)


def getStatusDisease_by_Category(request,id):

    a = Imageskin.objects.values('disease', 'disease__category').annotate(Count('disease')).filter(disease__category=id)

    # idc = list(a.values_list('disease__category__id'))
    name = list(a.values_list('disease__name'))
    count = list(a.values_list('disease__count'))

    data = {}
    data['datasets'] = {}
    data['datasets']['data'] = count
    data['datasets']['backgroundColor'] = ['#ff6384','#ff9f40','#ffcd56','#4bc0c0','#36a2eb']
    data['datasets']['label'] = 'Por tipo'
    data['labels'] = name
    return JsonResponse(data)


def getStatusSource_by_Category(request,id):

    a = Imageskin.objects.values('sourcedata', 'disease__category').annotate(Count('sourcedata')).filter(
        disease__category=id)

    # idc = list(a.values_list('disease__category__id'))
    name = list(a.values_list('sourcedata__name'))
    count = list(a.values_list('sourcedata__count'))

    data = {}
    data['datasets'] = {}
    data['datasets']['data'] = count
    data['datasets']['backgroundColor'] = ['#ff6384','#ff9f40','#ffcd56','#4bc0c0','#36a2eb']
    data['datasets']['label'] = 'Por fuente'
    data['labels'] = name
    return JsonResponse(data)


def changeState(request):

    model_opc = request.POST['model']
    idc = request.POST['id']
    data_state = request.POST['state']

    if model_opc == 'category':
        model_aux = get_object_or_404(Category, pk=idc)
    elif model_opc == 'disease':
        model_aux = get_object_or_404(Disease, pk=idc)
    elif model_opc == 'imageskin':
        model_aux = get_object_or_404(Imageskin, pk=idc)

    if data_state == "true":
        data_state = True
    else:
        data_state = False

    model_aux.state = data_state
    model_aux.save()

    data = {}
    data['status'] = True
    data['state'] = data_state
    data['msg'] = 'Cambio realizado.'
    return JsonResponse(data)


def state(request, category_id):
    category = get_object_or_404(Category,pk=category_id)

    if 'state' in request.POST:
        value = True
    else:
        value = False

    category.state = value
    category.save()

    return HttpResponseRedirect(reverse('catalogo:results', args=(category_id,)))


def commentPush(request):

    data = {}
    if request.user.is_authenticated:
        userLog = request.user.id
    else:
        userLog = False

    idU = User.objects.get(pk=request.user.id)
    idI = Imageskin.objects.get(pk=request.POST['idx'])
    text = request.POST['text']
    textCount = len(text)

    if textCount == 0:
        data['status'] = False

catalogo/templates/catalogo/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Categoria</title>
</head>
<body>
    <h1>{{ category.name }}</h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'catalogo:state' category.id %}" method="post">
        {% csrf_token %}

        <input type="checkbox" name="state" id="state" value="{{ category.state }}" {% if category.state %}checked{% endif %}>
        <label for="state">On/Off</label>
        <input type="submit" value="Guardar">
    </form>



    <ul>
        {% for disease in category.disease_set.all %}
            <li>{{ disease.name }}</li>
        {% endfor %}
    </ul>
</body>
</html>

catalogo/templates/catalogo/diseases.html
{% extends 'catalogo/main/base.html' %}
{% load static %}


{# CSS #}
{% block stylesheet %}
    <link href="{% static 'catalogo/plugins/bootstrap-toggle/css/bootstrap-toggle.min.css' %}" rel="stylesheet">
{% endblock stylesheet %}



{# CONTENIDO #}
{% block contenido %}

    <!-- Introduction Row -->
    <div class="row skin-introduction">
        <div class="col-lg-12">
            <h1>
                <a href="{% url 'catalogo:index' %}"><i class="fa fa-database skin-ico" aria-hidden="true"></i></a>
                {{ category.name }}
                <input id="toggle-event" data-id="{{ category.id }}" type="checkbox" {% if category.state %}checked{% endif %} data-toggle="toggle" data-size="small" data-onstyle="default">
            </h1>
            <p>{{ category.detail }}</p>
        </div>
    </div>
    <!-- /.row -->

    <div class="row skin-body">
    {% for disease in category.disease_set.all %}

        <div class="col-lg-4 col-sm-6 text-center skin-conte-circle">
            <div class="skin-circle img-responsive img-center img-circle" style="background-image: url('{{ disease.cover|default:"rick" }}')">
                <a href="{% url 'catalogo:imageskin' disease.id %}"></a>
            </div>

            <h3>{{ disease.name }}
                <small>{{ disease.count_images }}</small>
            </h3>
            <p>{{ disease.pub_date|date:'d/m/Y H:i' }}</p>
        </div>

    {% endfor %}
    </div>

{% endblock contenido %}


{# JAVASCRIPT #}
{% block javascript %}

    <script src="{% static 'catalogo/plugins/bootstrap-toggle/js/bootstrap-toggle.min.js' %}"></script>

    <script>

        $('#toggle-event').change(function () {

            $.ajax({
                type: 'POST',
                url: '/catalogo/changeState',
                dataType: 'json',
                data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    'model': 'category',
                    'id': $(this).attr('data-id'),
                    'state': $(this).prop('checked'),
                },

                success: function (data, textStatus) {
		            //alert(data, textStatus);
                    $('#skin-message').html(data['msg']).removeClass().addClass('alert alert-success').click()

		            // $('#output').html(data); // append to inner html
		        },

		        error: function(xhr, status, e) {
		            alert(status, e);
		        }
            });
        });

    </script>
{% endblock javascript %}

catalogo/templates/catalogo/imageskin.html
{% extends 'catalogo/main/base.html' %}
{% load static %}


{# CSS #}
{% block stylesheet %}
    <link href="{% static 'catalogo/plugins/bootstrap-toggle/css/bootstrap-toggle.min.css' %}" rel="stylesheet">
    <link href="{% static 'catalogo/css/pinterest-like.css' %}" rel="stylesheet">
    <link href="{% static 'catalogo/plugins/lightbox/dist/ekko-lightbox.min.css' %}" rel="stylesheet">
    {% if user.is_authenticated %}
        <style>
            .skinWeb .modal-dialog{
                max-width: 2000px !important;
            }
        </style>
    {% endif %}

{% endblock stylesheet %}



{# CONTENIDO #}
{% block contenido %}
    <!-- Introduction Row -->
    <div class="row skin-introduction">
        <div class="col-lg-12">
            <h1>
                <a href="{% url 'catalogo:index' %}"><i class="fa fa-database skin-ico" aria-hidden="true"></i></a>
                <a href="{% url 'catalogo:diseases' disease.category_id %}">{{ disease.category.name}}</a> / {{ disease.name }}
                <input id="toggle-event" data-id="{{ disease.id }}" type="checkbox" {% if disease.state %}checked{% endif %} data-toggle="toggle" data-size="small" data-onstyle="default">
            </h1>
            <p>{{ disease.detail }}</p>
        </div>
    </div>
    <!-- /.row -->

    <ul id="waterfall" class=""></ul>
    <div class="loading-img"></div>
    <div id="more_images">
        <button id="prueba" data-url="{% url 'catalogo:loadImageskin' disease.id 1 %}"><i class="fa fa-chevron-circle-down" aria-hidden="true"></i></button>
    </div>
{% endblock contenido %}


{# JAVASCRIPT #}
{% block javascript %}
    <script src="{% static 'catalogo/plugins/bootstrap-toggle/js/bootstrap-toggle.min.js' %}"></script>
    <script src="{% static 'catalogo/plugins/pinterest-style/newWaterfall.js' %}"></script>
    <script src="{% static 'catalogo/plugins/lightbox/dist/ekko-lightbox.js' %}"></script>

    <script>
        var gate = 0;
        var numPage = 1;
        $(document).ready(function() {

            $('#waterfall').NewWaterfall({
                width:260,
            });

            // Cambia el estado de activo e inactivo
            $('#toggle-event').change(function (){
                $.ajax({
                    type: 'POST',
                    url: '/catalogo/changeState',
                    dataType: 'json',
                    data: {
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        'model': 'disease',
                        'id': $(this).attr('data-id'),
                        'state': $(this).prop('checked'),
                    },

                    success: function (data, textStatus) {
                        $('#skin-message').html(data['msg']).removeClass().addClass('alert alert-success').click()
                    },

                    error: function(xhr, status, e) {
                        alert(status, e);
                    }
                });
            });

            // Cambia el estado de activo e inactivo
            $('body').on('change','#toggle-event-image', function () {

                idImage = $(this).data('id');
                $.ajax({
                    type: 'POST',
                    url: '/catalogo/changeState',
                    dataType: 'json',
                    data: {
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        'model': 'imageskin',
                        'id': $(this).attr('data-id'),
                        'state': $(this).prop('checked'),
                    },

                    success: function (data, textStatus) {
                        $list = $('#list-'+idImage+' > div');

                        if (data.state)
                            $list.removeClass('image-bug').find('i').remove();
                        else
                            $list.addClass('image-bug').prepend('<i class="fa fa-bug" aria-hidden="true"></i>');


                    },

                    error: function(xhr, status, e) {
                        alert(status, e);
                    }
                });
            });


            $('#prueba').click(function () {
                urlx = '/catalogo/imageskin/{{ disease.id }}/'+ numPage +'/';
                console.log(urlx);

                scroll_load_data(urlx);
            });

            //  Close Modal
            $('body').on('click','i.image-view-close',function () {
                $('.modal-header button.close').click();
            });

            // hacer comentario en imagen
            $('body').on('click','.image-view-input span',function (){
                $('ul.chat li.error-msg').remove();
                $.ajax({
                    type: 'POST',
                    url: '/catalogo/commentPush',
                    dataType: 'json',
                    data: {
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        'idx': $('.image-view-pic').data('id'),
                        'text': $('#comment-image-skin').val(),
                    },

                    success: function (data, textStatus) {
{#                        $('#skin-message').html(data['msg']).removeClass().addClass('alert alert-success').click()#}
                        console.log(data);
                        if (data.status){
                            $('ul.chat').prepend(
                                '<li class="right clearfix">'+
                                    '<span class="chat-img">'+data.nameshort+'</span>'+
                                    '<div class="chat-body clearfix">'+
                                        '<div class="header">'+
                                            '<strong class="pull-right primary-font">'+data.nameUser+'</strong>'+
                                            '<small class=" text-muted"><span class="glyphicon glyphicon-time"></span>Reciente</small>'+
                                        '</div>'+
                                        '<p>'+$('#comment-image-skin').val()+'</p>'+
                                    '</div>'+
                                '</li>').promise().done(function () {
{#                                    haux = $('div.panel-body').height()#}
{#                                    $('div.panel-body').scrollTop(haux);#}
                                    $('#comment-image-skin').val('');
                                });

                        }else{
                            $('ul.chat').prepend('<li class="error-msg"><p class="bg-danger">'+data.msg+'</p></li>');
                        }
                    },

                    error: function(xhr, status, e) {
                        alert(status, e);
                    }
                });
            });
        });


        // funcion para cargar mas imagenes
        var scroll_load_data = function (urlx) {

            if (gate==0)
            {
                gate = 1;
                $('.loading-img').html('<i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i>');

                $.ajax({
                    type: 'POST',
                    url: urlx,
                    dataType: 'json',
                    data: {
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                    },
                    success: function (data, textStatus) {
                        if (data.data) {
                            $('#waterfall').append(data.data).promise().done(function () {
                                gate = 0;
                                numPage++;
                                $('.loading-img').html('');
                            })
                        }else{
                            $('.loading-img').html('<p>No hay mas resultados...</p>');
                        }
                    },
                    error: function(xhr, status, e) {
                        alert(status, e);
                    }
                });
            }
        };

        // Cargar datos - event scroll
        setInterval(function(){
			if($(window).scrollTop() >= $(document).height() - $(window).height() + 0  && !gate)
			{
                console.log('abierto');
				urlx = '/catalogo/imageskin/{{ disease.id }}/'+ numPage +'/';
                console.log(urlx);
                scroll_load_data(urlx);
			}
		},60);

        // Para el modal
        $(document).delegate('*[data-toggle="lightbox"]:not([data-gallery="navigateTo"])', 'click', function(event) {
            event.preventDefault();
            return $(this).ekkoLightbox({
                onContentLoaded: function () {
                    var a = $('.image-view .image-view-pic img');
                    console.log(a[0].width);
                    console.log(a[0].height);
                    console.log(a.parent().height());
                    if (a[0].width > a[0].height || a.parent().height() > a[0].height){
                        a.addClass('centered-image');
                    }
                },
                onShown: function() {
                    if (window.console) {
                        return console.log('Checking our the events huh?');
                    }
                },
                onNavigate: function(direction, itemIndex) {
                    if (window.console) {
                        return console.log('Navigating '+direction+'. Current item: '+itemIndex);
                    }
                },
                always_show_close : false,
                loadingMessage : '<i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i>',
            });
        });

    </script>
{% endblock javascript %}

catalogo/templates/catalogo/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Resultados</title>
</head>
<body>

    <h1>{{ category.name }}</h1>
    <p>{{ category.state }}</p>

    <a href="{% url 'catalogo:detail' category.id %}">back?</a>
</body>
</html>